name: CI

on:
  pull_request:
    branches:
      - backend-refactor
  workflow_dispatch:

jobs:
  pre-commit:
    name: pre-commit checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch all branches
        run: git fetch --all

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"

      - name: Install pyright
        run: npm install -g pyright
      - name: Install Python and pre-commit
        run: |
          pip install pre-commit==3.6.1

      - name: Run pre-commit checks
        run: pre-commit run --all-files
